name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  payu:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu
  retrofit: ^4.1.0
dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
flutter:
  uses-material-design: true
  assets:
    - lib/mock/
