name: payu_about
description: Flutter package with Payu About dialog

version: 1.0.0-beta.2
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  payu_core: 
    path: ../payu_core
  payu_state_management: 
    path: ../payu_state_management
  payu_translations: 
    path: ../payu_translations

dev_dependencies:
  build_runner: ^2.2.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter: 
