name: payu
description: Flutter package which gives a set of components for pay-by-link, one-time card payments, storing card options, scanning card data, and one-click payments (Google Pay, Apple Pay, BLIK).

version: 0.0.1-alpha.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  payu_about: 
    path: ../payu_about
  payu_add_card: 
    path: ../payu_add_card
  payu_api: 
    path: ../payu_api
  payu_core: 
    path: ../payu_core
  payu_mastercard_installments: 
    path: ../payu_mastercard_installments
  payu_mobile_payments: 
    path: ../payu_mobile_payments/payu_mobile_payments
  payu_payment_methods: 
    path: ../payu_payment_methods
  payu_terms_and_conditions: 
    path: ../payu_terms_and_conditions
  payu_three_ds: 
    path: ../payu_three_ds
  payu_translations: 
    path: ../payu_translations
  payu_web_payments: 
    path: ../payu_web_payments

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.0.0
  flutter_lints: ^1.0.0

flutter:



