name: payu
description: Flutter package which gives a set of components for pay-by-link, one-time card payments, storing card options, scanning card data, and one-click payments (Google Pay, Apple Pay, BLIK).
version: 1.1.0
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  payu_add_card:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_add_card
      ref: 1.1.0
  payu_api:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_api
      ref: 1.1.0
  payu_core:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core
      ref: 1.1.0
  payu_interface:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_interface
      ref: 1.1.0
  payu_mobile_payments:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments
      ref: 1.1.0
  payu_payment_methods:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_payment_methods
      ref: 1.1.0
  payu_terms_and_conditions:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_terms_and_conditions
      ref: 1.1.0
  payu_three_ds:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_three_ds
      ref: 1.1.0
  payu_translations:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
      ref: 1.1.0
  payu_web_payments:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_web_payments
      ref: 1.1.0
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
      ref: 1.1.0
dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
