name: payu_payment_methods
description: Flutter package which allows to present available POS payment methods easy
version: 1.0.7
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  payu_add_card:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_add_card
      ref: 1.0.7
  payu_core:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core
      ref: 1.0.7
  payu_state_management:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_state_management
      ref: 1.0.7
  payu_translations:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
      ref: 1.0.7
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
      ref: 1.0.7
dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
