name: payu_interface
description: Flutter package with Payu interface which allows to access the main properties directly.

version: 1.0.2
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:

dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.0

flutter:
