name: payu_state_management
description: Flutter package with Payu interface which allows to use wrapper over state management.
version: 1.0.3
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  payu_interface:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_interface
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
  provider: ^6.1.5
dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
