name: payu_state_management
description: Flutter package with Payu interface which allows to use wrapper over state management.
version: 1.0.3
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  payu_interface:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_interface
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
  provider: ^6.0.3
dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
