name: payu_mastercard_installments
description: Flutter package that allows Mastercard card holders to split payments into monthly installments
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  payu_state_management:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_state_management
  payu_translations:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
flutter:
