name: payu_mobile_payments_ios
description: Flutter package with iOS (ApplePay) implementation for payu_mobile_payment

version: 1.0.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  dependency_validator: ^3.2.2
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PayuMobilePaymentsIosPlugin
