name: payu_mobile_payments_ios
description: Flutter package with iOS (ApplePay) implementation for payu_mobile_payment

version: 1.1.0
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PayuMobilePaymentsIosPlugin
