name: payu_mobile_payments
description: Flutter plugin which allows make payments via Apple Pay / Google Pay
version: 1.0.7
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_mobile_payments_android:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments_android
      ref: 1.0.7
  payu_mobile_payments_ios:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments_ios
      ref: 1.0.7
  payu_mobile_payments_platform_interface:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments_platform_interface
      ref: 1.0.7
dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        default_package: payu_mobile_payments_android
      ios:
        default_package: payu_mobile_payments_ios
