name: payu_mobile_payments
description: Flutter plugin which allows make payments via Apple Pay / Google Pay
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_mobile_payments_android:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments_android
  payu_mobile_payments_ios:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments_ios
  payu_mobile_payments_platform_interface:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_mobile_payments/payu_mobile_payments_platform_interface
dev_dependencies:
  build_runner: ^2.4.8
  dependency_validator: ^3.2.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        default_package: payu_mobile_payments_android
      ios:
        default_package: payu_mobile_payments_ios
