name: payu_add_card
description: Flutter package which allows to tokenize cards via Payu
version: 1.0.3
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  payu_api:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_api
  payu_core:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core
  payu_state_management:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_state_management
  payu_terms_and_conditions:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_terms_and_conditions
  payu_translations:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  http: ^1.4.0
  mockito: ^5.4.4
