name: payu_mobile_payments_android
description: Flutter package with Android (GooglePay) implementation for payu_mobile_payment

version: 1.0.0-beta.1
publish_to: none

homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.payu_mobile_payments_android
        pluginClass: PayuMobilePaymentsAndroidPlugin
