name: payu_terms_and_conditions
description: Flutter package with Payu Terms and Conditions widget
version: 1.0.3
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_core:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core
  payu_state_management:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_state_management
  payu_translations:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
  payu_ui:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_ui
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
flutter:
