name: payu_three_ds
description: Flutter package which allows to handle Payu 3DS.
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_api:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_api
  payu_core:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_core
  payu_state_management:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_state_management
  payu_translations:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_translations
  webview_flutter: ^3.0.4
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  webview_flutter_platform_interface: any
