name: payu_ui
description: Flutter package with Payu UI elements.
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_interface:
    git:
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu_interface
  provider: ^6.0.3
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
flutter:
